# Version 2023-03-05
name: Java CI
on: [push, pull_request]

jobs:
  build:
    uses: guusdk/openfire-plugin-builder-action/.github/workflows/openfire-plugin-build.yml@Java-17
    secrets:
      IGNITE_REALTIME_MAVEN_USERNAME: ${{ secrets.IGNITE_REALTIME_MAVEN_USERNAME }}
      IGNITE_REALTIME_MAVEN_PASSWORD: ${{ secrets.IGNITE_REALTIME_MAVEN_PASSWORD }}
